name: Slack Integration

on:
  push:
    branches: '*'

jobs:
  send-notification:
    name: Send Slack Notification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '14'


      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":" :error: :loading: GitHub Action performed successfully!:happy:"}' $SLACK_WEBHOOK_URL
